apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-learning-lab-cluster-119
  namespace: flink-learning-lab-iceberg
spec:
  image: flink:1.19-java11
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "4"
    web.cancel.enable: 'true'

    env.hadoop.conf.dir: "/hadoop/etc/hadoop"

    fs.s3a.impl.disable.cache: "true"
    classloader.parent-first-patterns.defaults: 'java.;scala.;org.apache.flink.;org.apache.kafka.;org.apache.hadoop.;software.amazon.;org.apache.iceberg.;org.apache.parquet.'

    web.submit.enable: "true"

  serviceAccount: flink-sa
  jobManager:
    replicas: 1
    resource:
      memory: 16G
      cpu: 4
  taskManager:
    replicas: 3
    resource:
      memory: 8G
      cpu: 4
  podTemplate:
    spec:
      initContainers:
        - name: python-init
          image: python:3.10.12-slim
          command:
            - /bin/sh
            - -c
            - |
              pip3 install apache-flink==2.0.1

              mkdir -p /python/link/bin
              mkdir -p /python/link/lib

              cp -r /usr/local/bin/* /python/link/bin/
              cp -r /usr/local/lib/* /python/link/lib/

          volumeMounts:
            - name: flink-python-bin-volume
              mountPath: /python/link/bin
            - name: flink-python-lib-volume
              mountPath: /python/link/lib
        - name: flink-lib-init
          image: flink:1.19.3-scala_2.12-java11
          command:
            - /bin/sh
            - -c
            - |
              cp -r /opt/flink/lib/* /flink-libs
              rm -rf /flink-libs/flink-shaded-hadoop-2-uber*
              cp -r /opt/flink/plugins/* /flink-plugins
              
              cp -r /usr/local/bin/* /python/link/bin

          volumeMounts:
            - name: flink-lib-volume
              mountPath: /flink-libs
            - name: flink-plugin-volume
              mountPath: /flink-plugins
            - name: flink-python-bin-volume
              mountPath: /python/link/bin
            - name: flink-python-lib-volume
              mountPath: /python/link/lib
        - name: dependency-downloader
          image: apache/hadoop:3.3.5
          command:
            - /bin/sh
            - -c
            - |

              cp -r /opt/hadoop/* /hadoop
              
              cd /flink-libs
              
              # hive Metastore 접근 세팅
              wget https://repo1.maven.org/maven2/org/apache/hive/hive-exec/3.1.3/hive-exec-3.1.3.jar
              wget https://repo1.maven.org/maven2/org/apache/thrift/libfb303/0.9.3/libfb303-0.9.3.jar
              wget https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar
              
              # JDBC 접근 세팅
              wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar
              wget https://repo1.maven.org/maven2/io/github/therealhieu/flink-connector-clickhouse/1.19.0-1.0.0/flink-connector-clickhouse-1.19.0-1.0.0.jar
              wget https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc/3.3.0-1.19/flink-connector-jdbc-3.3.0-1.19.jar
              wget https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/3.5.6/mariadb-java-client-3.5.6.jar
              # wget https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.5.0/mysql-connector-j-9.5.0.jar

              # Kafka 세팅
              wget https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.3.0-1.19/flink-sql-connector-kafka-3.3.0-1.19.jar
              wget https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.3.0/kafka-clients-3.3.0.jar
              wget https://repo1.maven.org/maven2/org/apache/flink/flink-avro/1.19.3/flink-avro-1.19.3.jar
              wget https://repo1.maven.org/maven2/org/apache/flink/flink-avro-confluent-registry/1.19.3/flink-avro-confluent-registry-1.19.3.jar
              wget https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/7.0.16/kafka-schema-registry-client-7.0.16.jar
              wget https://repo1.maven.org/maven2/org/apache/avro/avro/1.10.2/avro-1.10.2.jar
              wget https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.13.5/jackson-databind-2.13.5.jar
              wget https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.13.5/jackson-core-2.13.5.jar
              wget https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.13.5/jackson-annotations-2.13.5.jar
              
              mkdir -p /flink-plugins/s3-fs-hadoop
              
              # iceberg 세팅
              wget -P /flink-plugins/s3-fs-hadoop https://repo1.maven.org/maven2/org/apache/flink/flink-s3-fs-hadoop/1.19.3/flink-s3-fs-hadoop-1.19.3.jar
              wget https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-flink-runtime-1.19/1.6.0/iceberg-flink-runtime-1.19-1.6.0.jar
              
              # paimon 세팅
              wget https://repo.maven.apache.org/maven2/org/apache/paimon/paimon-flink-1.19/1.3.0/paimon-flink-1.19-1.3.0.jar
                  
              # MinIO 세팅
              wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar
              
              # hadoop 3.3.5 세팅
              cp /hadoop/share/hadoop/common/hadoop-common-3.3.5.jar /flink-libs
              cp /hadoop/share/hadoop/common/lib/commons-configuration2-2.8.0.jar /flink-libs
              cp /hadoop/share/hadoop/common/lib/stax2-api-4.2.1.jar /flink-libs
              cp /hadoop/share/hadoop/common/lib/commons-logging-1.1.3.jar /flink-libs
              cp /hadoop/share/hadoop/common/lib/hadoop-shaded-guava-1.1.1.jar /flink-libs
              cp /hadoop/share/hadoop/common/lib/hadoop-auth-3.3.5.jar /flink-libs
              cp /hadoop/share/hadoop/common/lib/woodstox-core-5.4.0.jar /flink-libs
              cp /hadoop/share/hadoop/hdfs/hadoop-hdfs-client-3.3.5.jar /flink-libs
              cp /hadoop/share/hadoop/mapreduce/hadoop-mapreduce-client-core-3.3.5.jar /flink-libs
              wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.5/hadoop-aws-3.3.5.jar

          volumeMounts:
            - name: flink-lib-volume
              mountPath: /flink-libs
            - name: flink-plugin-volume
              mountPath: /flink-plugins
            - name: hadoop
              mountPath: /hadoop
      containers:
        - name: flink-main-container
          env:
            - name: TZ
              value: Asia/Seoul
            - name: HADOOP_HOME
              value: /hadoop
            - name: HADOOP_CLASSPATH
              value: /hadoop/etc/hadoop:/hadoop/share/hadoop/common/lib/*:/hadoop/share/hadoop/common/*:/hadoop/share/hadoop/hdfs:/hadoop/share/hadoop/hdfs/lib/*:/hadoop/share/hadoop/hdfs/*:/hadoop/share/hadoop/mapreduce/*:/hadoop/share/hadoop/yarn:/hadoop/share/hadoop/yarn/lib/*:/hadoop/share/hadoop/yarn/*
          volumeMounts:
            - name: hadoop
              mountPath: /hadoop
            - name: flink-lib-volume
              mountPath: /opt/flink/lib
            - name: flink-plugin-volume
              mountPath: /opt/flink/plugins
      volumes:
        - name: flink-lib-volume
          emptyDir: { }
        - name: flink-plugin-volume
          emptyDir: { }
        - name: flink-python-bin-volume
          emptyDir: { }
        - name: flink-python-lib-volume
          emptyDir: { }
        - name: hadoop
          emptyDir: { }
  mode: standalone

